apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jmanus
  namespace: default
  labels:
    app: jmanus
spec:
  ingressClassName: nginx
  rules:
    - host: jmanus.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jmanus
                port:
                  number: 18080
