/*
 * Copyright 2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.cloud.ai.lynxe.workspace.conversation.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.alibaba.cloud.ai.lynxe.recorder.entity.vo.PlanExecutionRecord;
import com.alibaba.cloud.ai.lynxe.recorder.service.PlanHierarchyReaderService;
import com.alibaba.cloud.ai.lynxe.workspace.conversation.entity.vo.Memory;
import com.alibaba.cloud.ai.lynxe.workspace.conversation.entity.vo.MemoryResponse;
import com.alibaba.cloud.ai.lynxe.workspace.conversation.service.MemoryService;

/**
 * @author dahua
 * @time 2025/8/5
 * @desc memory controller
 */
@RestController
@RequestMapping("/api/memories")
@CrossOrigin(origins = "*") // Add cross-origin support
public class MemoryController {

	private static final Logger logger = LoggerFactory.getLogger(MemoryController.class);

	@Autowired
	private MemoryService memoryService;

	@Autowired
	private PlanHierarchyReaderService planHierarchyReaderService;

	@GetMapping
	public ResponseEntity<MemoryResponse> getAllMemories() {
		try {
			List<Memory> memories = memoryService.getMemories();
			return ResponseEntity.ok(MemoryResponse.success(memories));
		}
		catch (Exception e) {
			return ResponseEntity.ok(MemoryResponse.error("Failed to retrieve memories: " + e.getMessage()));
		}
	}

	@GetMapping("/single")
	public ResponseEntity<MemoryResponse> singleMemory(@RequestParam String conversationId) {
		try {
			Memory memory = memoryService.singleMemory(conversationId);
			return ResponseEntity.ok(MemoryResponse.success(memory));
		}
		catch (IllegalArgumentException e) {
			return ResponseEntity.ok(MemoryResponse.notFound());
		}
		catch (Exception e) {
			return ResponseEntity.ok(MemoryResponse.error("Failed to retrieve memory: " + e.getMessage()));
		}
	}

	@PostMapping
	public ResponseEntity<MemoryResponse> createMemory(@RequestBody Memory memory) {
		try {
			Memory createdMemory = memoryService.saveMemory(memory);
			return ResponseEntity.ok(MemoryResponse.created(createdMemory));
		}
		catch (Exception e) {
			return ResponseEntity.ok(MemoryResponse.error("Failed to create memory: " + e.getMessage()));
		}
	}

	@PutMapping
	public ResponseEntity<MemoryResponse> updateMemory(@RequestBody Memory memory) {
		try {
			Memory updatedMemory = memoryService.updateMemory(memory);
			return ResponseEntity.ok(MemoryResponse.updated(updatedMemory));
		}
		catch (IllegalArgumentException e) {
			return ResponseEntity.ok(MemoryResponse.notFound());
		}
		catch (Exception e) {
			return ResponseEntity.ok(MemoryResponse.error("Failed to update memory: " + e.getMessage()));
		}
	}

	@DeleteMapping("/{conversationId}")
	public ResponseEntity<MemoryResponse> deleteMemory(@PathVariable String conversationId) {
		try {
			memoryService.deleteMemory(conversationId);
			return ResponseEntity.ok(MemoryResponse.deleted());
		}
		catch (Exception e) {
			return ResponseEntity.ok(MemoryResponse.error("Failed to delete memory: " + e.getMessage()));
		}
	}

	/**
	 * @deprecated This endpoint is deprecated. Conversation IDs are now automatically
	 * generated by the backend when not provided in request. Use the main execution
	 * endpoints which accept conversationId as an optional parameter.
	 */
	@Deprecated
	@GetMapping("/generate-id")
	public ResponseEntity<MemoryResponse> generateConversationId() {
		try {
			String conversationId = memoryService.generateConversationId();
			// Create a simple response with the generated ID
			MemoryResponse response = new MemoryResponse(true, "Conversation ID generated successfully");
			response.setData(new Memory(conversationId, "Generated Conversation"));
			return ResponseEntity.ok(response);
		}
		catch (Exception e) {
			return ResponseEntity.ok(MemoryResponse.error("Failed to generate conversation ID: " + e.getMessage()));
		}
	}

	/**
	 * Get conversation history (plan execution records) for a specific conversation ID
	 * @param conversationId The conversation ID
	 * @return List of plan execution records for this conversation
	 */
	@GetMapping("/{conversationId}/history")
	public ResponseEntity<?> getConversationHistory(@PathVariable String conversationId) {
		try {
			logger.info("Retrieving conversation history for conversationId: {}", conversationId);

			// Get the memory entity to find all associated rootPlanIds
			Memory memory = memoryService.singleMemory(conversationId);
			if (memory == null) {
				logger.warn("No memory found for conversationId: {}", conversationId);
				return ResponseEntity.ok(new ArrayList<>());
			}

			List<String> rootPlanIds = memory.getRootPlanIds();
			if (rootPlanIds == null || rootPlanIds.isEmpty()) {
				logger.info("No plan execution records found for conversationId: {}", conversationId);
				return ResponseEntity.ok(new ArrayList<>());
			}

			logger.info("Found {} rootPlanIds for conversationId: {}", rootPlanIds.size(), conversationId);

			// Retrieve all plan execution records for these rootPlanIds
			List<PlanExecutionRecord> planRecords = rootPlanIds.stream().map(rootPlanId -> {
				try {
					PlanExecutionRecord record = planHierarchyReaderService.readPlanTreeByRootId(rootPlanId);
					if (record == null) {
						logger.warn("No plan execution record found for rootPlanId: {}", rootPlanId);
					}
					return record;
				}
				catch (Exception e) {
					logger.error("Error retrieving plan record for rootPlanId: {}", rootPlanId, e);
					return null;
				}
			})
				.filter(record -> record != null) // Filter out null records
				.collect(Collectors.toList());

			logger.info("Successfully retrieved {} plan execution records for conversationId: {}", planRecords.size(),
					conversationId);

			return ResponseEntity.ok(planRecords);
		}
		catch (IllegalArgumentException e) {
			logger.warn("Conversation not found: {}", conversationId);
			return ResponseEntity.ok(new ArrayList<>());
		}
		catch (Exception e) {
			logger.error("Error retrieving conversation history for conversationId: {}", conversationId, e);
			return ResponseEntity.status(500).body("Failed to retrieve conversation history: " + e.getMessage());
		}
	}

}
