apiVersion: v2
name: jmanus
description: A Helm chart for JManus - AI Agent Management System
type: application
version: 0.1.0
appVersion: "4.0.3-SNAPSHOT"
keywords:
  - ai
  - agent
  - spring-boot
  - kubernetes
home: https://github.com/alibaba/spring-ai-alibaba
sources:
  - https://github.com/alibaba/spring-ai-alibaba
maintainers:
  - name: Alibaba Cloud AI
    email: spring-ai-alibaba@alibaba-inc.com