apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jmanus.fullname" . }}-config
  labels:
    {{- include "jmanus.labels" . | nindent 4 }}
data:
  # Application configuration
  application.yml: |
    server:
      port: {{ .Values.app.port }}
    spring:
      application:
        name: {{ .Values.app.name }}
      profiles:
        active: {{ .Values.app.profile }}
      main:
        allow-circular-references: true
        lazy-initialization: false
      aop:
        proxy-target-class: true
      servlet:
        multipart:
          max-file-size: 1073741824
          max-request-size: 6442450944
          enabled: true
          file-size-threshold: 2048
      datasource:
        hikari:
          maximum-pool-size: 20
          minimum-idle: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
          pool-name: Spring-AI-Alibaba-JManus-{{ .Values.app.profile }}-Pool
          connection-test-query: SELECT 1
          validation-timeout: 5000
          leak-detection-threshold: 60000
      jpa:
        show-sql: false
        properties:
          hibernate:
            format_sql: true
      ai:
        autoconfigure:
          exclude:
            - org.springframework.ai.model.chat.client.autoconfigure.ChatClientAutoConfiguration
    logging:
      file:
        name: ./logs/info.log
      level:
        root: INFO
        com.alibaba.cloud.ai.example.manus.inhouse.registry.McpToolRegistry: INFO
        com.alibaba.cloud.ai.example.manus.tool: DEBUG
        com.alibaba.cloud.ai.example.manus.inhouse.tool: DEBUG
        com.alibaba.cloud.ai.manus.agent: DEBUG
        com.alibaba.cloud.ai.manus.llm: DEBUG
        org.springframework.web.reactive.function.client: DEBUG
    manus:
      plan:
        polling:
          enable-polling: true
          max-attempts: 60
          poll-interval: 2000
          connect-timeout: 5000
          read-timeout: 10000
          base-backoff-delay: 1000
          max-backoff-delay: 10000
      file-upload:
        max-file-size: 1073741824
        max-files-per-upload: 10
        upload-directory: uploaded_files
        validation-strategy: code
    namespace:
      value: default
    agent:
      init: true
      serialize: jackson

  # Database-specific configuration
  {{- if eq .Values.app.profile "h2" }}
  application-h2.yml: |
    spring:
      datasource:
        url: {{ .Values.database.h2.url }}
        driver-class-name: org.h2.Driver
        username: {{ .Values.database.h2.username }}
        password: {{ .Values.database.h2.password }}
      h2:
        console:
          enabled: true
          path: /h2-console
          settings:
            web-allow-others: true
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: update
        show-sql: false
      ai:
        memory:
          h2:
            enabled: true
  {{- else if eq .Values.app.profile "mysql" }}
  application-mysql.yml: |
    spring:
      datasource:
        url: {{ .Values.database.mysql.url }}
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: {{ .Values.database.mysql.username }}
        password: {{ .Values.database.mysql.password }}
      jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
      ai:
        memory:
          mysql:
            enabled: true
  {{- else if eq .Values.app.profile "postgres" }}
  application-postgres.yml: |
    spring:
      datasource:
        url: {{ .Values.database.postgres.url }}
        driver-class-name: org.postgresql.Driver
        username: {{ .Values.database.postgres.username }}
        password: {{ .Values.database.postgres.password }}
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ai:
        memory:
          postgres:
            enabled: true
  {{- end }}

  # Docker environment configuration
  application-docker.yml: |
    manus:
      browser:
        headless: {{ .Values.app.headless }}
        requestTimeout: 180
      openBrowserAuto: false
    spring:
      jpa:
        properties:
          hibernate:
            format_sql: false
    logging:
      level:
        root: INFO