#
# Copyright 2024-2025 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: 🏗️ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./tools/github-actions/setup-deps

      - name: Install tools
        run: make tools

      - name: Build UI
        run: make ui-build

      - name: Build project
        run: make build

      - name: Run tests
        run: make test

      - name: Read VERSION file
        id: version
        run: echo "BUILD_VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Verify JAR file exists
        run: |
          if [ -f "target/jmanus-${{ steps.version.outputs.BUILD_VERSION }}.jar" ]; then
            echo "✅ JAR file found: target/jmanus-${{ steps.version.outputs.BUILD_VERSION }}.jar"
            ls -lh target/jmanus-${{ steps.version.outputs.BUILD_VERSION }}.jar
          else
            echo "❌ JAR file not found: target/jmanus-${{ steps.version.outputs.BUILD_VERSION }}.jar"
            echo "Files in target directory:"
            ls -la target/*.jar || echo "No JAR files found"
            exit 1
          fi
